baseURL = 'https://vinci128.github.io/'
languageCode = 'en-us'
locale = 'en-us'
title = 'Rough Drafts of Reason'
theme = "hugo-PaperMod"

author = "vinci128"
description = "Thoughts on culture, society, and life"

[params]
  homeInfoParams = ""
  socialIcons = []

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
